---
- include_tasks: generate-root.yml
- include_tasks: generate.yml
- include_tasks: generate-backend.yml
  when:
    - backend_certificate_needed or rabbitmq_enable_tls | bool
- include_tasks: generate-libvirt.yml
  when: certificates_generate_libvirt | bool
